language: cpp

git:
  depth: 1

jobs:
  include:
  - name: Android
    language: android
    env:
    - NDK_DIR=$HOME/android-ndk
    android:
      components:
      - android-27
    addons:
      apt:
        packages:
        - gradle
    cache:
      directories:
      - $HOME/sfml-cache
    before_script:
      - yes | sdkmanager --licenses
    script:
      - chmod +x tests/travis_android.sh
      - tests/travis_android.sh

